---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: centos
  tags: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  remote_user: centos
  tags: vector
  roles:
    - vector

- name: Install Nginx, Lighthouse
  hosts: lighthouse
  remote_user: centos
  tags: ["nginx", "lighthouse"]
  roles:
    - nginx
    - lighthouse
