---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: centos
  tags: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          tags: get_distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          tags: get_distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      tags: install_distrib
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      tags: check
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  remote_user: centos
  tags: vector
  tasks:
    - name: Install vector distrib
      become: true
      tags: install_distrib
      ansible.builtin.yum:
        name:
          - "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}\
          -{{ vector_minor_version }}.{{ ansible_architecture }}.rpm"
    - name: Check vector works correctly
      ansible.builtin.command: "vector --version"
      tags: check
      register: vector_checked
      failed_when: vector_checked.rc != 0
      changed_when: vector_checked == 0

- name: Install Lighthouse
  hosts: lighthouse
  remote_user: centos
  tags: lighthouse
  tasks:
    - name: Install unzip
      become: true
      tags: install_distrib
      ansible.builtin.yum:
        name: unzip
        state: present
    - name: Install EPEL repo
      become: true
      tags: install_distrib
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Install Nginx
      become: true
      tags: install_distrib
      ansible.builtin.yum:
        name: nginx
    - name: Download Lighthouse ZIP
      ansible.builtin.get_url:
        url: "{{ lighthouse_zip }}"
        dest: ./master.zip
    - name: Extract Lighthouse ZIP
      tags: install_distrib
      become: true
      ansible.builtin.unarchive:
        src: ./master.zip
        dest: /usr/share/nginx/html
        remote_src: true
    - name: Allow connections on 80 port
      tags: configure
      become: true
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_ports:
          - "80"
        jump: ACCEPT
    - name: Copy Nginx config
      tags: configure
      become: true
      ansible.builtin.copy:
        src: ./confs/nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: '0644'
    - name: Start Nginx service
      become: true
      service:
        name: nginx
        state: started
